// Copyright (c) 2026 9Ashwin. SPDX-License-Identifier: MIT

package runtime

import (
	"context"
	"encoding/json"

	"github.com/spf13/cobra"

	"github.com/9Ashwin/one-cli/auth"
	"github.com/9Ashwin/one-cli/metadata"
	"github.com/9Ashwin/one-cli/output"
	"github.com/9Ashwin/one-cli/vfs"
)

// Runtime assembles a cobra command tree from metadata.
type Runtime struct {
	deps Deps
	root *cobra.Command
}

// New creates a Runtime from dependencies. It returns an error if the metadata
// spec is nil or has no services.
func New(deps Deps) (*Runtime, error) {
	if deps.Meta == nil {
		return nil, errInternal("metadata spec is nil")
	}
	if len(deps.Meta.Services) == 0 {
		return nil, errInternal("metadata spec has no services")
	}
	if deps.Auth == nil {
		deps.Auth = noAuth{}
	}
	if deps.Client == nil {
		return nil, errInternal("client is nil")
	}
	if deps.Output == nil {
		deps.Output = output.New(output.FormatJSON)
	}
	if deps.VFS == nil {
		deps.VFS = vfs.NewOS()
	}

	r := &Runtime{deps: deps}
	r.root = r.buildRootCmd()
	return r, nil
}

// RootCmd returns the assembled root cobra command.
func (r *Runtime) RootCmd() *cobra.Command {
	return r.root
}

func (r *Runtime) render(cmd *cobra.Command, v any) error {
	format, _ := cmd.Flags().GetString("format")
	f := output.New(output.Format(format))
	return f.Format(cmd.OutOrStdout(), v)
}

func (r *Runtime) buildRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:   r.deps.Meta.CLIName,
		Short: r.deps.Meta.CLIName + " — Agent-Native CLI",
		Long:  r.deps.Meta.CLIName + " generated by one-cli (https://github.com/9Ashwin/one-cli).",
	}
	root.PersistentFlags().String("format", string(output.FormatPretty), "Output format: json|pretty|table|ndjson|csv")
	root.PersistentFlags().Bool("dry-run", false, "Show the request without executing it")
	root.PersistentFlags().String("as", string(r.deps.Meta.DefaultIdentity), "Identity to use: user|bot")

	// Generic api METHOD /path command.
	root.AddCommand(r.buildAPICmd())

	// Service/resource/method commands.
	for _, svc := range sortedServices(r.deps.Meta.Services) {
		root.AddCommand(r.buildServiceCmd(svc))
	}
	return root
}

func sortedServices(services map[string]metadata.Service) []metadata.Service {
	var names []string
	for n := range services {
		names = append(names, n)
	}
	// Simple insertion-sort to avoid importing sort for a small list.
	for i := 1; i < len(names); i++ {
		for j := i; j > 0 && names[j-1] > names[j]; j-- {
			names[j-1], names[j] = names[j], names[j-1]
		}
	}
	out := make([]metadata.Service, len(names))
	for i, n := range names {
		out[i] = services[n]
	}
	return out
}

func jsonUnmarshal(data []byte, v any) error {
	return json.Unmarshal(data, v)
}

// discardWriter is an io.Writer that ignores writes. Used when cobra output
// capture is not needed.
type discardWriter struct{}

func (discardWriter) Write(p []byte) (int, error) { return len(p), nil }

// noAuth is a no-op CredentialProvider used when none is supplied.
type noAuth struct{}

func (noAuth) Token(_ context.Context, _ auth.Identity) (auth.Token, error) {
	return auth.Token{}, nil
}

// Ensure noAuth implements the interface at compile time.
var _ auth.CredentialProvider = noAuth{}
